version: '2'

volumes:
  streaming:
  database:
  fedora:
  work:
  solr:
    
services:
  db:
    image: avalonmediasystem/db:fedora4
    build: ./db
    volumes:
      - database:/data
    environment:
      - AVALON_DB_PASSWORD
      - FEDORA_DB_PASSWORD
      - PGDATA=/data
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
  fedora:
    image: avalonmediasystem/fedora:4.7.5
    build: 
      context: ./fedora
      args:
        - FEDORA_DB_PASSWORD
        - FEDORA_VERSION=4.7.5
    depends_on:
      - db
    volumes:
      - fedora:/data
    ports:
      - "8984:8080"
  solr:
    image: avalonmediasystem/solr:latest
    build: 
      context: ./solr
      args:
        - AVALON_BRANCH
    ports:
      - "8983:8983"
    volumes:
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - avalon
      - /opt/solr/avalon_conf
  matterhorn:
    image: avalonmediasystem/matterhorn
    build: 
      context: ./matterhorn
      args:
        - MATTERHORN_VER=1.4
        - MATTERHORN_BRANCH=1.4.x
    volumes:
      - ./masterfiles:/masterfiles
      - streaming:/streamfiles
      - work:/work
    ports:
      - "8080:8080"
  hls:
    image: avalonmediasystem/nginx
    build:
      context: ./nginx
    volumes:
      - streaming:/data
    ports:
       - "8880:80"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  avalon:
    image: docker.lib.umd.edu/avalon:6.4.3-bcm-0${TAG_SUFFIX}-SNAPSHOT
    build: 
      context: ./avalon
      args:
        - AVALON_REPO
        - AVALON_BRANCH
        - SECRET_KEY_BASE
        - BASE_URL
        - DATABASE_URL=postgres://avalon:${AVALON_DB_PASSWORD}@db/avalon
        - BUNDLE_WITH=${BUNDLE_WITH}
        - BUNDLE_WITHOUT=development:test:profiling:mysql
    depends_on:
      - db
      - fedora
      - solr
      - redis
    environment:
      - APP_NAME
      - SECRET_KEY_BASE
      - ASSET_HOST
      - SETTINGS__DOMAIN__HOST
      - DATABASE_URL=postgres://avalon:${AVALON_DB_PASSWORD}@db/avalon
      - SETTINGS__DROPBOX__PATH=/masterfiles/dropbox
      - SETTINGS__DROPBOX__UPLOAD_URI=./masterfiles/dropbox
      - EMAIL_COMMENTS
      - EMAIL_NOTIFICATION
      - EMAIL_SUPPORT
      - FEDORA_BASE_PATH
      - FEDORA_NAMESPACE=avalon
      - FEDORA_URL=http://fedoraAdmin:fedoraAdmin@fedora:8080/fedora/rest
      - SETTINGS__FFMPEG_PATH=/usr/bin/ffmpeg
      - MASTER_FILE_PATH
      - SETTINGS__ACTIVE_JOB__QUEUE_ADAPTER
      - RAILS_GROUPS
      - MASTER_FILE_STRATEGY=delete
      - MATTERHORN_URL=http://matterhorn_system_account:CHANGE_ME@matterhorn:8080/
      - SETTINGS__MATTERHORN__MEDIA_PATH=/masterfiles
      - MEDIAINFO_PATH=/usr/bin/mediainfo
      - RAILS_ENV=production
      - SETTINGS__REDIS__HOST=redis
      - SETTINGS__REDIS__PORT=6379
      - SMTP_ADDRESS
      - SMTP_AUTHENTICATION
      - SMTP_DOMAIN
      - SMTP_ENABLE_STARTTLS_AUTO
      - SMTP_OPENSSL_VERIFY_MODE
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_USER_NAME
      - SOLR_URL=http://solr:8983/solr/avalon
      - SETTINGS__STREAMING__CONTENT_PATH=/streamfiles
      - SETTINGS__STREAMING__HTTP_BASE=http://${STREAMING_HOST}:8880/avalon
      - SETTINGS__STREAMING__SERVER=nginx
      - SYSTEM_GROUPS=administrator,group_manager,manager
      - Z3950_ATTRIBUTE
      - Z3950_DATABASE
      - Z3950_HOST
      - Z3950_PORT
    volumes:
      - ./masterfiles:/masterfiles
      - ./gems:/gems
    ports:
      - "80:80"
